// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddCollege(arg1:string,arg2:string):Promise<void>;

export function AddProgram(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddStudent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function DeleteCollege(arg1:string):Promise<void>;

export function DeleteProgram(arg1:string):Promise<void>;

export function DeleteStudent(arg1:string):Promise<void>;

export function ListColleges():Promise<Array<models.College>>;

export function ListPrograms():Promise<Array<models.Program>>;

export function ListStudents():Promise<Array<models.Student>>;

export function UpdateCollege(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateProgram(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateStudent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;
