// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollege(arg1, arg2) {
  return window['go']['main']['App']['AddCollege'](arg1, arg2);
}

export function AddProgram(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProgram'](arg1, arg2, arg3);
}

export function AddStudent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddStudent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteCollege(arg1) {
  return window['go']['main']['App']['DeleteCollege'](arg1);
}

export function DeleteProgram(arg1) {
  return window['go']['main']['App']['DeleteProgram'](arg1);
}

export function DeleteStudent(arg1) {
  return window['go']['main']['App']['DeleteStudent'](arg1);
}

export function ListColleges() {
  return window['go']['main']['App']['ListColleges']();
}

export function ListPrograms() {
  return window['go']['main']['App']['ListPrograms']();
}

export function ListStudents() {
  return window['go']['main']['App']['ListStudents']();
}

export function UpdateCollege(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCollege'](arg1, arg2, arg3);
}

export function UpdateProgram(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProgram'](arg1, arg2, arg3, arg4);
}

export function UpdateStudent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateStudent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
